// <auto-generated />
namespace FootballFixturesApp1.ApplicationContextMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Update51 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Update51));
        
        string IMigrationMetadata.Id
        {
            get { return "201705010024037_Update51"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
